version: "3.8"
services:
  react-app:
    build:
      context: .
      args:
        VITE_API_BASE_URL: "http://37.59.99.2:8080/api"
        VITE_API_UPLOADS_URL: "http://37.59.99.2:8080/"
    container_name: react-vite-app
    ports:
      - "3002:80"
    restart: always
