version: "3.8"
services:
  react-app:
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_UPLOADS_URL: ${VITE_API_UPLOADS_URL}
    container_name: react-vite-app
    ports:
      - "3002:80"
    restart: always
